# Generated by Django 4.2.10 on 2024-09-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='loan_status',
            field=models.CharField(blank=True, choices=[('貸出可', '貸出可'), ('貸出中', '貸出中'), ('貸出不可', '貸出不可'), ('その他', 'その他（説明欄に詳細）')], null=True),
        ),
    ]
