# Generated by Django 4.2.10 on 2024-09-12 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_equipment_loan_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='loan_status',
            field=models.CharField(blank=True, choices=[('貸出可', '貸出可'), ('貸出中', '貸出中'), ('貸出不可', '貸出不可'), ('その他', 'その他（説明欄に詳細）')], max_length=50, null=True),
        ),
    ]
