# Generated by Django 4.2.10 on 2024-09-17 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_alter_equipment_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='web_site',
            field=models.URLField(blank=True),
        ),
    ]
