# Generated by Django 4.2.10 on 2024-09-13 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_loan_date_order_return_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='approval_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
